const freeDays = {
  janeiro: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  fevereiro: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  marco: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  abril: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  maio: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  junho: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  julho: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  agosto: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  setembro: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  outubro: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  novembro: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
  dezembro: [
    { day: 1, status: "available", click: 0 },
    { day: 2, status: "available" },
    { day: 3, status: "available", click: 0 },
    { day: 4, status: "available", click: 0 },
    { day: 5, status: "available", click: 0 },
    { day: 6, status: "unavailable", click: 0 },
    { day: 7, status: "unavailable", click: 0 },
    { day: 8, status: "available", click: 0 },
    { day: 9, status: "available", click: 0 },
    { day: 10, status: "available", click: 0 },
    { day: 11, status: "available", click: 0 },
    { day: 12, status: "available", click: 0 },
    { day: 13, status: "unavailable", click: 0 },
    { day: 14, status: "unavailable", click: 0 },
    { day: 15, status: "available", click: 0 },
    { day: 16, status: "available", click: 0 },
    { day: 17, status: "available", click: 0 },
    { day: 18, status: "available", click: 0 },
    { day: 19, status: "available", click: 0 },
    { day: 20, status: "unavailable", click: 0 },
    { day: 21, status: "unavailable", click: 0 },
    { day: 22, status: "available", click: 0 },
    { day: 23, status: "available", click: 0 },
    { day: 24, status: "available", click: 0 },
    { day: 25, status: "available", click: 0 },
    { day: 26, status: "available", click: 0 },
    { day: 27, status: "unavailable", click: 0 },
    { day: 28, status: "unavailable", click: 0 },
    { day: 29, status: "available", click: 0 },
    { day: 30, status: "available", click: 0 },
  ],
};

export { freeDays as useDays };
