# VERSION: "3.9"

services:
  database_schedule:
    image: postgres
    container_name: database_schedule
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=schedule
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
